import { CameraView,useCameraPermissions } from 'expo-camera';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useState } from 'react';
import { Pressable,SafeAreaView,StyleSheet,Text,View } from 'react-native';
import { C,F } from '@/components/street-souk-ui';
import { useStreetSoukStore } from '@/context/street-souk-store';
const brands=['BOLAPSD.','IYOO CARTEL','BONFO','THE CHROME PILGRIM','GREATERTHAN00'];
export default function PassportScanScreen(){const router=useRouter();const [permission,requestPermission]=useCameraPermissions();const [scanned,setScanned]=useState<string|null>(null);const {passportStamps,addPassportStamp}=useStreetSoukStore();const award=(data:string)=>{if(scanned)return;const normalized=data.toLowerCase().replace(/[^a-z0-9]/g,'');const brand=data==='demo'?brands.find(b=>!passportStamps.includes(b)):brands.find(b=>normalized.includes(b.toLowerCase().replace(/[^a-z0-9]/g,'')));if(brand&&!passportStamps.includes(brand)){addPassportStamp(brand);setScanned(brand)}};return <SafeAreaView style={s.safe}><View style={s.header}><Pressable onPress={()=>router.back()}><Ionicons name="close" size={24} color={C.paper}/></Pressable><Text style={s.headerText}>STREET SOUK PASSPORT</Text><View style={{width:24}}/></View>{scanned?<View style={s.center}><Ionicons name="checkmark-circle" size={56} color={C.green}/><Text style={s.title}>STAMP COLLECTED</Text><Text style={s.copy}>{scanned} is now in your passport.</Text><Pressable style={s.button} onPress={()=>router.replace('/passport')}><Text style={s.buttonText}>VIEW PASSPORT</Text></Pressable></View>:!permission?.granted?<View style={s.center}><Ionicons name="qr-code-outline" size={48} color={C.green}/><Text style={s.title}>COLLECT A STAMP</Text><Text style={s.copy}>Scan the QR displayed at a participating brand booth.</Text><Pressable style={s.button} onPress={requestPermission}><Text style={s.buttonText}>ALLOW CAMERA</Text></Pressable><Pressable style={s.demo} onPress={()=>award('demo')}><Text style={s.demoText}>TRY A DEMO STAMP</Text></Pressable></View>:<View style={s.cameraWrap}><CameraView style={s.camera} facing="back" barcodeScannerSettings={{barcodeTypes:['qr']}} onBarcodeScanned={({data})=>award(data)}><View style={s.frame}/><View style={s.bottom}><Text style={s.hint}>SCAN THE CODE AT A BRAND BOOTH</Text><Pressable style={s.demo} onPress={()=>award('demo')}><Text style={s.demoText}>TRY A DEMO STAMP</Text></Pressable></View></CameraView></View>}</SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg},header:{height:62,paddingHorizontal:18,borderBottomWidth:1,borderBottomColor:C.line,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},headerText:{color:C.muted,fontFamily:F.mono,fontSize:9},center:{flex:1,alignItems:'center',justifyContent:'center',padding:28},title:{color:C.paper,fontFamily:F.display,fontSize:31,marginTop:14,textAlign:'center'},copy:{color:C.muted,fontFamily:F.body,fontSize:16,lineHeight:22,textAlign:'center',marginTop:8},button:{marginTop:23,padding:14,backgroundColor:C.green},buttonText:{color:C.ink,fontFamily:F.mono,fontSize:11},demo:{marginTop:16,padding:12,borderWidth:1,borderColor:C.green},demoText:{color:C.green,fontFamily:F.mono,fontSize:10},cameraWrap:{flex:1,padding:17},camera:{flex:1,backgroundColor:C.panel,alignItems:'center',justifyContent:'center'},frame:{width:250,height:250,borderWidth:2,borderColor:C.green},bottom:{position:'absolute',bottom:22,alignItems:'center'},hint:{color:C.paper,backgroundColor:C.bg,padding:10,fontFamily:F.mono,fontSize:9}});
