import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { C, F } from '@/components/street-souk-ui';

function SettingRow({ icon, title, detail, value, onPress }: { icon: keyof typeof Ionicons.glyphMap; title: string; detail: string; value: boolean; onPress: () => void }) {
  return <Pressable accessibilityRole="switch" accessibilityState={{ checked: value }} onPress={onPress} style={s.row}><View style={s.rowIcon}><Ionicons name={icon} size={20} color={value ? C.neon : C.muted} /></View><View style={s.rowCopy}><Text style={s.rowTitle}>{title}</Text><Text style={s.rowDetail}>{detail}</Text></View><View style={[s.toggle, value && s.toggleOn]}><View style={[s.toggleKnob, value && s.toggleKnobOn]} /></View></Pressable>;
}

export default function SettingsScreen() {
  const router = useRouter(); const [notifications, setNotifications] = useState(true); const [guidance, setGuidance] = useState(true); const [motion, setMotion] = useState(false);
  return <SafeAreaView style={s.safe}><View style={s.header}><Pressable accessibilityLabel="Go back" onPress={() => router.back()} style={s.back}><Ionicons name="arrow-back" size={22} color={C.paper} /></Pressable><Text style={s.headerTitle}>SETTINGS</Text><View style={s.headerSpacer} /></View><ScrollView contentContainerStyle={s.content}><Text style={s.kicker}>STREET SOUK / PREFERENCES</Text><Text style={s.title}>YOUR SETUP</Text><View style={s.rule} /><Pressable onPress={() => router.push("/my-souk")} style={s.mySouk}><Ionicons name="heart-outline" size={20} color={C.ink} /><Text style={s.mySoukText}>OPEN MY SOUK</Text><Ionicons name="arrow-forward" size={18} color={C.ink} /></Pressable><Text style={s.section}>APP EXPERIENCE</Text><SettingRow icon="notifications-outline" title="FESTIVAL ALERTS" detail="Get live updates about drops and stages." value={notifications} onPress={() => setNotifications((v) => !v)} /><SettingRow icon="navigate-outline" title="ROUTE GUIDANCE" detail="Keep route instructions visible on the map." value={guidance} onPress={() => setGuidance((v) => !v)} /><SettingRow icon="pause-outline" title="REDUCED MOTION" detail="Use calmer transitions throughout the app." value={motion} onPress={() => setMotion((v) => !v)} /><Text style={s.section}>MAP & DATA</Text><Pressable onPress={() => router.push("/scan")} style={s.action}><Ionicons name="qr-code-outline" size={20} color={C.neon} /><View style={s.rowCopy}><Text style={s.rowTitle}>SCAN A VENUE QR</Text><Text style={s.rowDetail}>Set your starting point from a venue marker.</Text></View><Ionicons name="chevron-forward" size={20} color={C.muted} /></Pressable><Pressable style={s.action}><Ionicons name="information-circle-outline" size={20} color={C.neon} /><View style={s.rowCopy}><Text style={s.rowTitle}>ABOUT STREET SOUK</Text><Text style={s.rowDetail}>Festival map data and app information.</Text></View><Ionicons name="chevron-forward" size={20} color={C.muted} /></Pressable></ScrollView></SafeAreaView>;
}

const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: C.bg }, header: { height: 72, borderBottomWidth: 2, borderBottomColor: C.line, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20 }, back: { width: 40, height: 40, borderWidth: 1, borderColor: C.line, alignItems: 'center', justifyContent: 'center' }, headerTitle: { color: C.neon, fontFamily: F.display, fontSize: 22 }, headerSpacer: { width: 40 }, content: { padding: 24, paddingBottom: 44 }, kicker: { color: C.muted, fontFamily: F.mono, fontSize: 10 }, title: { color: C.neon, fontFamily: F.display, fontSize: 38, marginTop: 5 }, rule: { height: 2, backgroundColor: C.line, marginTop: 10, marginBottom: 30 }, mySouk: { backgroundColor: C.green, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 20 }, mySoukText: { color: C.ink, fontFamily: F.display, fontSize: 18, flex: 1 }, section: { color: C.neon, fontFamily: F.mono, fontSize: 10, marginBottom: 10, marginTop: 8 }, row: { minHeight: 78, borderTopWidth: 1, borderTopColor: C.line, flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 12 }, rowIcon: { width: 38, height: 38, borderWidth: 1, borderColor: C.line, alignItems: 'center', justifyContent: 'center' }, rowCopy: { flex: 1 }, rowTitle: { color: C.paper, fontFamily: F.mono, fontSize: 11 }, rowDetail: { color: C.muted, fontFamily: F.body, fontSize: 14, marginTop: 4 }, toggle: { width: 42, height: 23, borderWidth: 1, borderColor: C.muted, padding: 3, justifyContent: 'center' }, toggleOn: { backgroundColor: C.neon, borderColor: C.neon }, toggleKnob: { width: 15, height: 15, backgroundColor: C.muted }, toggleKnobOn: { backgroundColor: C.ink, alignSelf: 'flex-end' }, action: { minHeight: 78, borderTopWidth: 1, borderTopColor: C.line, flexDirection: 'row', alignItems: 'center', gap: 12 }, });
